### ISSUE TITLE
Websockets trait

### ISSUE THREAD

**Issue by steffenix** [nash-io/openlimits#30]
In order to start supporting websockets connections we should define what should be the basic traits

**Comment by mankinskin** [comment]
what exactly does the websocket connect to? to binance and coinbase?
are we looking for a shared api between openlimits and remote exchanges?
or is there something else openlimits should be able to connect with?
should it expose a websocket endpoint itself? or only act as a client?

**Comment by steffenix** [comment]
Exchanges are using WebSockets to push updates to the client (such as orderbook updates)
The trait should be built to have a standard way of getting orderbook updates across multiple exchanges.

**Comment by acatinon** [comment]
So, there are several kind of exchange WebSockets implementations:

* With some exchanges, there is only one "generic" endpoint to connect to and then subscribe to one or more "services" by sending messages to the WS
* Some exchanges provides an endpoint for each service (with the ability to subscribe to the given market if applicable)
* Some exchanges provides both methods above
* Finally, some exchanges give the ability to subscribe to one or more service when connecting to a "generic" endpoint by passing parameters to the endpoint url (so there is no need to send additional message)

Back to openLimits, the idea is to have a `ExchangeStreams` trait with a method `new_stream` that returns a `WebSocketStream<E: Exchange>` struct, with the ability to subscribe to one or more services at once.

Also, if the exchange allows it, a `ExchangeMuttableStreams` trait with 2 methods `subscribe` and `unsubscribe` to send messages to a WS endpoint for adding or removing subscriptions

If E impl `ExchangeMuttableStreams`, `subscribe` and `unsubscribe` methods are automatically added to `WebSocketStream<E: Exchange>`.

If an exchange impl `ExchangeStreams`, we can add default methods like `get_order_book_stream` that calls `new_stream` with the rights parameters.

@Ejhfast what do you think? I did a draft PR with a first iteration: #108

**Comment by Ejhfast** [comment]
Thanks for this @acatinon! This proposal aligns pretty closely with what I started doing in the other PR but then reversed due to the amount of work involved and concerns about the architecture. Here are a two other approaches I could see working for how OpenLimits exposes the stream to users:
1. The subscribe endpoint returns a new Stream/Channel which outputs just the events from the intended subscription. Then user code manages that however they like (this is the approach I took in the underling [Nash client](https://github.com/nash-io/nash-rust/blob/master/nash-native-client/src/ws_client/client.rs#L963)). This would abstract away what is going on behind the scenes (whether there is only one endpoint or many, etc.) and each call to subscribe would always return a new Stream/Channel with independent data
2. Alternatively, OpenLimits might not expose the stream at all and instead allow the user to pass in a callback fn that will be executed upon new events. This could be subscription specific (callback is passed to each `subscribe` and only executes on the associated subscription) or one callback could be provided globally. I used this architecture to expose openlimits subscriptions to Python devs in the [Python wrapper](https://github.com/nash-io/openlimits-python/blob/master/src/lib.rs#L183).

On your suggestion, I like enforcing an `unsubscribe` in the trait. I'm not sure I understand the benefit of the `new_stream` method. Ideally, I think OpenLimits should abstract away as much as possible. Just letting the user `subscribe` and `unsubscribe` as they like is a pretty nice, simple model.

**Comment by acatinon** [comment]
Personally I prefer streams, but it's subjective... Anyway, from a stream, you can execute a callback on new events simply with a `for_each()`. Doing callback -> stream seems more complicated, and if you take the OpenLimils internal logic into account, it's stream -> callback -> stream. Looks like suboptimized...

About `new_stream`, in my mind, `subscribe` take only one subscription as a parameter, and `new_stream` is used to create a new stream on one or more subscription, but yeah, we can merge into `subscribe`.

To sum up, let's take an example: As an OpenLimits user, I want to be notified each time the ticker change both `btc_usdt` and `eth_usdt` markets.

```Rust
let stream = binanceWs.subscribe(
    &[Subscription::Ticker("btc_usdt"), Subscription::Ticker("eth_usdt")]
);
```

Binance WS API allows to specify multiple subscriptions in the endpoint querystring, so there is 1 open connection and 0 subscribe messages sent.

Now we want to replace to `eth_usdt` ticker by the level2 orderbook`:

```Rust
stream.subscribe(Subscription::Ticker("eth_usdt"));
stream.unsubscribe(Subscription::OrderBook("eth_usdt"));
```

One subscription message and one unsubscription message are sent to the open connection.

Some exchanges won't allow this (because ticker and level 2 order book are 2 different endpoint for instance), so that exchange won't impl `ExchangeMuttableStreams`, `subscribe` and `unsubscribe` methods won't be available on `stream` object, and the user will have no choice but calling `otherExchangeWs.subscribe` again to create a new stream (that's why I named this method `new_stream` in the first place).

**Comment by Ejhfast** [comment]
I think the main benefit of a callback approach is that the user of the library doesn't need to worry about setting up a process to iterate over the stream and react to events. Instead, they can just provide a callback function that is capable of operating over some shared mutable state. In the current `ExchangeWs` trait, setting up the process loop is a bit of a hassle because the WS client is both itself a stream and also used to initiate new subscription requests, so you need some shared state to push new messages into the process. You also need to provide a mechanism to signal to the process loop to shutdown when you are done with it. I guess in summary I would consider returning the stream directly to be a much lower level API. I'll try to put together a quick code sample to illustrate what I mean. Low level APIs aren't intrinsically bad, obviously; it depends on the use case. So I also agree either way that we should continue to support returning streams directly for other users who want it.

More generally, I think we should also do as much as possible to abstract away the difference between how WS are implemented on various exchanges. I don't think OpenLimits users should need to know or care about how that works (e.g., whether an exchange provides one endpoint or many, supports multiple simultaneous subscriptions or not, and so on). 

One small example to illustrate: suppose some exchange doesn't allow `unsubscribe` on a WS endpoint. We could still allow the user to "unsubscribe" via OpenLimits in various ways. One dumb but workable idea would be to ignore any new messages that come in that match the arguments to the unsubscribe call, once user has called it. Another approach (probably bad) would be to kill that WS connection behind the scenes and set up a new one with the existing subscriptions minus the one removed, where the consumer of stream doesn't know the difference. Anything is possible, really, it's just a matter of the exchange bindings doing the work to comply with the abstractions provided to the user. Though if we make the abstractions too arduous that would slow down the addition of new exchanges to the library, so there are always tradeoffs.

**Comment by acatinon** [comment]
So, let's focus on the public API to begin. A first naive implementation would be like this:

```Rust
exchangeSubscription.subscribe(Subscription::Trades("btcusdt".to_string()), |message| {
    // callback impl
}).await.unwrap();

exchangeSubscription.unsubscribe(Subscription::Trades("btcusdt".to_string()));
```
With this approach, there is no way to cancel the callback, we can only cancel all callbacks related to a subscription.

A solution would be to have the callback return an enum with Continue or Stop. Another idea may be something like this:
```Rust
let handle = exchangeSubscription.subscribe(Subscription::Trades("btcusdt".to_string()), |message| {
    // callback impl
}).await.unwrap();

// when we want to unsubscribe
drop(handle);
```
It seems more flexible. What do you think?

**Comment by Ejhfast** [comment]
Hey @acatinon sorry for the slow response on this, have been out+sick this week. I like this approach and the second version (dropping the handle to unsubscribe) looks very good to me. Would be happy to help review or contribute to code in that direction

We already discussed, but I think it would be good as well to keep the lower level API where the user can consume the stream of incoming events directly too

**Comment by acatinon** [comment]
No worries, I hope that you're getting better!

I continue to work on this topic, there is the `ExchangeWs` trait I have so far:

```Rust
pub trait ExchangeWs: Sized {
    type InitParams;
    type Subscription;

    async fn new(params: Self::InitParams) -> Self;

    async fn subscribe<
        S: Into<Self::Subscription> + Clone + Sync + Send,
        F: Fn(&Result<OpenLimitsWebsocketMessage>) + Sync + Send + 'static,
    >(
        &self,
        subscription: S,
        callback: F,
    ) -> Result<CallbackHandle<Result<OpenLimitsWebsocketMessage>>>;

    async fn create_stream<'a, S: Into<Self::Subscription> + Clone + Sync + Send>(
        &'a self,
        subscriptions: &[S],
    ) -> Result<SubscriptionStream<'a, Self>>;
}
```

The idea behind `Into<Self::Subscription>` is that we could subscribe to standardized channels across all exchanges, but also exchange specific channels:

```Rust
exchangeWs.subscribe(Subscription::Trades("btcusdt".to_string()), |_| {
    // callback impl
});

binanceWs.subscribe(BinanceSubscription::MiniTickerAll, |_| {
    // callback impl
});

```

It's still an experiment at this point, I hope I'm going somewhere...

**Comment by acatinon** [comment]
I also wonder what is the purpose of having 2 structs `OpenLimits` and `OpenLimitsWs` ?

**Comment by steffenix** [comment]
having multiple traits give some flexibility when adding a new exchange or if openlimits adds the futures exchanges, nash doesn't have any future products.
